-- =========================
-- USERS
-- =========================
CREATE TABLE app_users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(80)  NOT NULL,
    last_name  VARCHAR(80)  NOT NULL,
    email      VARCHAR(150) NOT NULL,
    password   VARCHAR(255),
    user_role  VARCHAR(20)  NOT NULL,
    CONSTRAINT uk_app_users_email UNIQUE (email)
);

-- =========================
-- STUDENTS
-- =========================
CREATE TABLE students
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_index VARCHAR(30)  NOT NULL,
    major         VARCHAR(120) NOT NULL,
    user_id       BIGINT       NOT NULL,
    CONSTRAINT uk_student_index UNIQUE (student_index),
    CONSTRAINT uk_student_user UNIQUE (user_id),
    CONSTRAINT fk_student_user
        FOREIGN KEY (user_id) REFERENCES app_users (id)
);

-- =========================
-- COURSES
-- =========================
CREATE TABLE courses
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code   VARCHAR(30)  NOT NULL,
    course_name   VARCHAR(200) NOT NULL,
    semester      INTEGER      NOT NULL,
    academic_year INTEGER      NOT NULL,
    CONSTRAINT uk_course_code_semester_year
        UNIQUE (course_code, semester, academic_year)
);

-- =========================
-- COURSE ENROLLMENTS
-- =========================
CREATE TABLE course_enrollments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    course_id  BIGINT NOT NULL,
    CONSTRAINT uk_course_student UNIQUE (course_id, student_id),
    CONSTRAINT fk_enrollment_student
        FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT fk_enrollment_course
        FOREIGN KEY (course_id) REFERENCES courses (id)
);

-- =========================
-- COURSE STAFF ASSIGNMENTS
-- =========================
CREATE TABLE course_staff_assignments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    course_id  BIGINT      NOT NULL,
    staff_role VARCHAR(20) NOT NULL,
    CONSTRAINT uk_course_user_staffrole
        UNIQUE (course_id, user_id, staff_role),
    CONSTRAINT fk_course_staff_user
        FOREIGN KEY (user_id) REFERENCES app_users (id),
    CONSTRAINT fk_course_staff_course
        FOREIGN KEY (course_id) REFERENCES courses (id)
);

-- =========================
-- EXAMS
-- =========================
CREATE TABLE exams
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session              VARCHAR(100) NOT NULL,
    date_of_exam         DATE         NOT NULL,
    capacity_of_students INTEGER      NOT NULL,
    start_time           TIME         NOT NULL,
    end_time             TIME         NOT NULL,
    course_id            BIGINT       NOT NULL,
    CONSTRAINT fk_exam_course
        FOREIGN KEY (course_id) REFERENCES courses (id)
);

-- =========================
-- EXAM RESERVED LABORATORIES
-- =========================
CREATE TABLE exam_reserved_labs
(
    exam_id    BIGINT       NOT NULL,
    laboratory VARCHAR(100) NOT NULL,
    CONSTRAINT fk_exam_reserved_labs_exam
        FOREIGN KEY (exam_id) REFERENCES exams (id),
    CONSTRAINT pk_exam_reserved_labs PRIMARY KEY (exam_id, laboratory)
);

-- =========================
-- STUDENT EXAM REGISTRATIONS
-- =========================
CREATE TABLE student_exam_registrations
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id  BIGINT      NOT NULL,
    exam_id     BIGINT      NOT NULL,
    exam_status VARCHAR(20) NOT NULL,
    CONSTRAINT uk_exam_student_registration
        UNIQUE (exam_id, student_id),
    CONSTRAINT fk_ser_student
        FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT fk_ser_exam
        FOREIGN KEY (exam_id) REFERENCES exams (id)
);

-- =========================
-- PASSWORD RESET TOKENS
-- =========================
CREATE TABLE password_reset_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token      VARCHAR(80) NOT NULL,
    user_id    BIGINT      NOT NULL,
    expires_at TIMESTAMP   NOT NULL,
    used       BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_prt_token UNIQUE (token),
    CONSTRAINT fk_prt_user
        FOREIGN KEY (user_id) REFERENCES app_users (id)
);

CREATE UNIQUE INDEX idx_prt_token ON password_reset_tokens (token);
